/var/spool/torque/mom_priv/jobs/532.localhost.SC: line 57: cd: /home/ynzhou/NCCTData/VIM4_fast5_test/0/workspace/Analysis/AdapterTrimmedFiles: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: barcode01: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_barcode01.log': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: barcode02: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_barcode02.log': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: barcode03: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_barcode03.log': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: barcode04: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_barcode04.log': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: barcode05: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_barcode05.log': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: barcode06: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_barcode06.log': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: barcode07: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_barcode07.log': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: barcode09: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_barcode09.log': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: barcode11: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_barcode11.log': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: barcode12: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_barcode12.log': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
cat: unclassified: Is a directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
mv: cannot stat 'log_filted_unclassified.log': No such file or directory
/var/spool/torque/mom_priv/jobs/532.localhost.SC: line 72: cd: /home/ynzhou/NCCTData/VIM4_fast5_test/0/workspace/Analysis/FiltedFiles: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/usr/local/lib/python2.7/dist-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures
/var/spool/torque/mom_priv/jobs/532.localhost.SC: line 80: cd: /home/ynzhou/NCCTData/VIM4_fast5_test/0/workspace/Analysis/AdapterTrimmedFiles: No such file or directory
/var/spool/torque/mom_priv/jobs/532.localhost.SC: line 82: /home/ynzhou/NCCTData/VIM4_fast5_test/0/Analysis/StatFiles/summary_stat_after_adaptertrimming.txt: No such file or directory
/var/spool/torque/mom_priv/jobs/532.localhost.SC: line 83: cd: /home/ynzhou/NCCTData/VIM4_fast5_test/0/workspace/Analysis/FiltedFiles: No such file or directory
/var/spool/torque/mom_priv/jobs/532.localhost.SC: line 84: /home/ynzhou/NCCTData/VIM4_fast5_test/0/Analysis/StatFiles/summary_stat_after_filter.txt: No such file or directory
